---
javascripts:
- base:
  - jquery-1.3.2.min
  - jquery-ui-1.7.2.custom.min
  - jquery_rails_ujs_helper
  - jquery.tablesorter.min
  - jquery.colorbox-min
  - application

- admin_base:
  - jquery-1.3.2.min
  - jquery-ui-1.7.2.custom.min
  - hoverIntent
  - superfish
  - jquery.lightbox-0.5.min
  - jquery_rails_ujs_helper
  - jquery.tablesorter.min
  - jquery.tablesorter.pager
  - jquery.tablednd.0.5
  - admin

stylesheets:
- base:
  - application
  - plugins/jquery.lightbox-0.5
  - tablesorter/tablesorter
  - colorbox

- admin_session:
  - session

- admin_base:
  - admin
  - plugins/jquery-ui-1.7.2.custom
  - plugins/jquery.lightbox-0.5
  - plugins/superfish
  - tablesorter/tablesorter
